#!/bin/sh
sudo dnf update
#sudo dnf install opencv opencv-devel python3-opencv python3-matplotlib python3-numpy
sudo dnf install python3-pip
pip install scikit-learn
pip install pandas
bash -c  "$(wget -qO- https://git.io/vQgMr)" 

sudo dnf config-manager --set-enabled fedora-cisco-openh264
sudo dnf install gstreamer1-plugin-openh264 mozilla-openh264
sudo dnf install gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-plugin-libav --exclude=gstreamer1-plugins-bad-free-devel
sudo dnf install lame\* --exclude=lame-devel
sudo dnf group upgrade --with-optional Multimedia
#https://www.tecmint.com/install-nvidia-drivers-in-linux/
#https://rpmfusion.org/Howto/NVIDIA
