#!/bin/sh

echo 'fastestmirror=True' | sudo tee -a /etc/dnf/dnf.conf
echo 'max_parallel_downloads=10' | sudo tee -a /etc/dnf/dnf.conf
echo 'defaultyes=True' | sudo tee -a /etc/dnf/dnf.conf
echo 'keepcache=True' | sudo tee -a /etc/dnf/dnf.conf

#sudo dnf update -y

##RPM Fusion##
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf config-manager --enable fedora-cisco-openh264
sudo dnf update @core

#install multimedia codecs
#sudo dnf config-manager --set-enabled fedora-cisco-openh264
#sudo dnf install gstreamer1-plugin-openh264 mozilla-openh264
#sudo dnf install gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-plugin-libav --exclude=gstreamer1-plugins-bad-free-devel -y
#sudo dnf install lame\* --exclude=lame-devel -y
#sudo dnf group upgrade --with-optional Multimedia -y

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
