#!/bin/sh

sudo dnf install opencv opencv-contrib opencv-doc python3-opencv python3-matplotlib python3-numpy -y
#sudo dnf install opencv opencv-devel
sudo dnf install python3-pip -y
pip install scikit-learn
pip install pandas

sudo dnf install gnome-tweaks gnome-extensions-app -y
sudo dnf install gimp gparted -y

#install multimedia codecs
sudo dnf config-manager --set-enabled fedora-cisco-openh264
sudo dnf install gstreamer1-plugin-openh264 mozilla-openh264
sudo dnf install gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-plugin-libav --exclude=gstreamer1-plugins-bad-free-devel -y
sudo dnf install lame\* --exclude=lame-devel -y
sudo dnf group upgrade --with-optional Multimedia -y

#Download Orchis-Theme
cd Documents
git clone "https://github.com/vinceliuice/Orchis-theme.git"
cd ..

flatpak install flathub com.usebottles.bottles -y

#sudo dnf install akmod-nvidia xorg-x11-drv-nvidia-cuda #x11 will become the only display system

#bash -c  "$(wget -qO- https://git.io/vQgMr)" #GOGH terminal color schemes
#set DNS 8.8.8.8,8.8.4.4
